version: 1.0.{build}
configuration: Release
platform: Any CPU
init:
- ps: 
environment:
  github_access_token:
    secure: D62s64pUE5r5MbjUus8aRsGGRbW0jUyu0cx3C2UhcFrDgBUXc8aMME01vaCgeiS3
  
before_build:
    - git config --global credential.helper store
    - ps: ac "$env:USERPROFILE\.git-credentials" "https://$($env:github_access_token):x-oauth-basic@github.com`n"
    - ps: Add-Content 1.txt "`nParts in more than one Product`n"
    - ps: cat 1.txt
    
build:
  project: appveyorTest.sln
  verbosity: minimal
  
on_success:
    - git config --global credential.helper store
    - ps: ac "$env:USERPROFILE\.git-credentials" "https://$($env:github_access_token):x-oauth-basic@github.com`n"
    - git add -A
    - git status
    - git diff --quiet --exit-code --cached || git commit --author="bianliu1013 <bianliu1013@163.com>" -m "Update azure powershell docs." 
    - git push -u origin master -f

 